package:
  name: nccl
  version: 1.3.4

source:
  git_url: https://github.com/NVIDIA/nccl.git 
  git_tag: v1.3.4-1

build:
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - cudatoolkit ==7.5

  run:
    - cudatoolkit ==7.5

about:
  home: https://github.com/NVIDIA/nccl
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Optimized primitives for collective multi-GPU communication
  description: |
    NCCL (pronounced "Nickel") is a stand-alone library of standard
    collective communication routines, such as all-gather, reduce, 
    broadcast, etc., that have been optimized to achieve high bandwidth
    over PCIe. NCCL supports an arbitrary number of GPUs installed in a
    single node and can be used in either single- or multi-process
    (e.g., MPI) applications.
